import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Providers from "@/lib/Providers/Providers";
import { Toaster } from "sonner";
import AppContainer from "@/components/Layout/AppContainer";

export const metadata: Metadata = {
  title: "Hall Management",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </head>
      <body>
        <Providers>
          <AppRouterCacheProvider>
            <AppContainer>
              <Toaster position="top-center" />
              {children}
            </AppContainer>
          </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
